# Generated by Django 5.2.8 on 2025-11-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_transcript', models.TextField()),
                ('commitments_text', models.TextField(blank=True, default='')),
                ('deadlines_text', models.TextField(blank=True, default='')),
                ('followups_text', models.TextField(blank=True, default='')),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
